name: Update CNAPS Data

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Start
        run: nr start

      - name: Check for Changes
        id: check_changes
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt || true
          echo "::set-output name=changed_files::$(cat changed_files.txt)"

      - name: Create PR if Changes Detected
        if: steps.check_changes.outputs.changed_files == 'assets/cities'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Update cities data'
          branch: main
